services:
  - type: web
    name: musichorn-bot
    env: docker
    region: frankfurt
    plan: free
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REFRESH_TOKEN
        sync: false
      - key: YANDEX_MUSIC_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false 